"""Tests for creative pipeline versioning, production fingerprinting, and cache invalidation."""

from pathlib import Path
import pytest

from app.domain.enums import VideoLifecycleState
from app.domain.models import Script, VideoProject
from app.media.director.models import ContentFormat
from app.media.director.profiles import (
    BENCHMARK_ANALYSIS_PROFILE,
    CODE_TUTORIAL_PROFILE,
    EDITORIAL_TECH_PROFILE,
)
from app.media.models import (
    CREATIVE_PIPELINE_VERSION,
    RenderManifest,
    compute_artifact_fingerprint,
    compute_production_fingerprint,
)
from app.media.pipeline import MediaProductionPipeline
from tests.media.test_media_pipeline import MockTTSBackend, repo_with_verified_project


def test_same_creative_configuration_reuses_cache(repo_with_verified_project, tmp_path: Path):
    """Identical creative configuration returns cached manifest without re-rendering."""
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_cache_reuse",
    )

    # First run
    proj_1, qa_1, manifest_1 = pipeline.run_production(project_id=project_id)
    assert proj_1.state == VideoLifecycleState.READY_FOR_REVIEW
    assert tts.call_count == 1
    assert manifest_1.creative_pipeline_version == CREATIVE_PIPELINE_VERSION
    assert manifest_1.request_fingerprint is not None
    assert manifest_1.artifact_fingerprint is not None

    # Second run (idempotent cache hit)
    proj_2, qa_2, manifest_2 = pipeline.run_production(project_id=project_id)
    assert proj_2.state == VideoLifecycleState.READY_FOR_REVIEW
    assert tts.call_count == 1  # TTS not called again
    assert manifest_2.production_fingerprint == manifest_1.production_fingerprint
    assert manifest_2.artifact_fingerprint == manifest_1.artifact_fingerprint
    assert manifest_2.final_video_sha256 == manifest_1.final_video_sha256


def test_changed_script_rebuilds_and_changes_fingerprint(repo_with_verified_project, tmp_path: Path):
    """Modifying script narration changes the production fingerprint and triggers a rebuild."""
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_script_rebuild",
    )

    # First run
    _, _, manifest_1 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 1

    # Modify the script narration
    project = repo.get_video_project(project_id)
    project.script.scenes[0].narration = "A completely updated narration for the first scene."
    project.state = VideoLifecycleState.VERIFIED
    repo.save_video_project(project)

    # Second run
    _, _, manifest_2 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 2
    assert manifest_2.production_fingerprint != manifest_1.production_fingerprint


def test_changed_creative_profile_rebuilds(repo_with_verified_project, tmp_path: Path):
    """Changing channel creative profile invalidates the cached manifest and forces re-render."""
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_profile_rebuild",
    )

    # First run with default / editorial profile
    pipeline.director.profile = EDITORIAL_TECH_PROFILE
    _, _, manifest_1 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 1
    assert manifest_1.creative_profile == EDITORIAL_TECH_PROFILE.name

    # Reset project state to VERIFIED for second run
    project = repo.get_video_project(project_id)
    project.state = VideoLifecycleState.VERIFIED
    repo.save_video_project(project)

    # Switch director profile to CODE_TUTORIAL_PROFILE
    pipeline.director.profile = CODE_TUTORIAL_PROFILE
    _, _, manifest_2 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 2  # Re-rendered due to profile mismatch
    assert manifest_2.creative_profile == CODE_TUTORIAL_PROFILE.name
    assert manifest_2.production_fingerprint != manifest_1.production_fingerprint


def test_changed_director_version_invalidates_legacy_cache(repo_with_verified_project, tmp_path: Path):
    """A manifest generated by an older director version is strictly invalidated."""
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_version_inval",
    )

    # First run
    _, _, manifest_1 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 1

    # Tamper with the cached manifest on disk to simulate a legacy pre-director-v2 manifest
    manifest_path = tmp_path / "out_version_inval" / project_id / "manifests" / "render_manifest.json"
    manifest_data = manifest_path.read_text(encoding="utf-8")
    # Replace version with legacy version
    legacy_manifest_data = manifest_data.replace(
        f'"creative_pipeline_version": "{CREATIVE_PIPELINE_VERSION}"',
        '"creative_pipeline_version": "director-legacy-v1"',
    )
    manifest_path.write_text(legacy_manifest_data, encoding="utf-8")

    # Reset project state to VERIFIED
    project = repo.get_video_project(project_id)
    project.state = VideoLifecycleState.VERIFIED
    repo.save_video_project(project)

    # Next run: must detect version mismatch and rebuild
    _, _, manifest_2 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 2
    assert manifest_2.creative_pipeline_version == CREATIVE_PIPELINE_VERSION


def test_changed_content_format_invalidates_cache(repo_with_verified_project, tmp_path: Path):
    """Switching content format from EXPLAINER to COMPARISON triggers rebuild."""
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_format_inval",
    )

    # First run with EXPLAINER
    project = repo.get_video_project(project_id)
    project.script.content_format = ContentFormat.EXPLAINER
    repo.save_video_project(project)

    _, _, manifest_1 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 1
    assert manifest_1.content_format == ContentFormat.EXPLAINER.value

    # Reset state and switch to COMPARISON
    project = repo.get_video_project(project_id)
    project.script.content_format = ContentFormat.COMPARISON
    project.state = VideoLifecycleState.VERIFIED
    repo.save_video_project(project)

    _, _, manifest_2 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 2
    assert manifest_2.content_format == ContentFormat.COMPARISON.value
    assert manifest_2.production_fingerprint != manifest_1.production_fingerprint


def test_artifact_fingerprint_changes_when_assets_change():
    """Different rendered visual asset hashes produce different artifact fingerprints."""
    req_fp = "request-fp-12345"
    assets_v1 = ["hash_shot_01_a", "hash_shot_02_a", "hash_shot_03_a"]
    assets_v2 = ["hash_shot_01_a", "hash_shot_02_MODIFIED", "hash_shot_03_a"]

    fp_1 = compute_artifact_fingerprint(
        request_fingerprint=req_fp,
        ordered_asset_hashes=assets_v1,
        audio_sha256="audio_sha_abc",
        subtitle_sha256="sub_sha_xyz",
    )
    fp_2 = compute_artifact_fingerprint(
        request_fingerprint=req_fp,
        ordered_asset_hashes=assets_v2,
        audio_sha256="audio_sha_abc",
        subtitle_sha256="sub_sha_xyz",
    )

    assert fp_1 != fp_2
    # Deterministic check
    assert fp_1 == compute_artifact_fingerprint(
        request_fingerprint=req_fp,
        ordered_asset_hashes=assets_v1,
        audio_sha256="audio_sha_abc",
        subtitle_sha256="sub_sha_xyz",
    )


# Alias for explicit regression test naming
test_artifact_fingerprint_changes_when_visual_assets_change = test_artifact_fingerprint_changes_when_assets_change


def test_director_v2_manifest_is_not_reused_by_director_v3(repo_with_verified_project, tmp_path: Path):
    """An old manifest tagged with director-v2 must strictly be rejected by director-v3."""
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_v2_rejection",
    )

    _, _, manifest_1 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 1
    assert manifest_1.creative_pipeline_version == "director-v3"

    # Overwrite manifest on disk to simulate old director-v2 manifest
    manifest_path = tmp_path / "out_v2_rejection" / project_id / "manifests" / "render_manifest.json"
    manifest_obj = RenderManifest.model_validate_json(manifest_path.read_text(encoding="utf-8"))
    manifest_dict = manifest_obj.model_dump()
    manifest_dict["creative_pipeline_version"] = "director-v2"
    manifest_dict["director_pipeline_version"] = "director-v2"
    manifest_path.write_text(RenderManifest(**manifest_dict).model_dump_json(indent=2), encoding="utf-8")

    # Reset project state to VERIFIED
    project = repo.get_video_project(project_id)
    project.state = VideoLifecycleState.VERIFIED
    repo.save_video_project(project)

    # Second run: must detect version mismatch and rebuild
    _, _, manifest_2 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 2
    assert manifest_2.creative_pipeline_version == "director-v3"


def test_old_passed_manifest_with_director_used_false_is_not_reused_in_fail_closed_mode(repo_with_verified_project, tmp_path: Path):
    """Even if an old manifest had qa_verdict == 'PASSED', if director_used is False, FAIL_CLOSED rejects it."""
    from app.media.director.models import CreativeFallbackPolicy
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_reject_director_false",
        fallback_policy=CreativeFallbackPolicy.FAIL_CLOSED,
    )

    _, _, manifest_1 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 1

    # Overwrite manifest to simulate old legacy slideshow manifest that passed QA
    manifest_path = tmp_path / "out_reject_director_false" / project_id / "manifests" / "render_manifest.json"
    manifest_obj = RenderManifest.model_validate_json(manifest_path.read_text(encoding="utf-8"))
    manifest_dict = manifest_obj.model_dump()
    manifest_dict["director_used"] = False
    manifest_dict["qa_verdict"] = "PASSED"
    manifest_path.write_text(RenderManifest(**manifest_dict).model_dump_json(indent=2), encoding="utf-8")

    # Reset project state to VERIFIED
    project = repo.get_video_project(project_id)
    project.state = VideoLifecycleState.VERIFIED
    repo.save_video_project(project)

    # Must reject cache reuse and rebuild with director
    _, _, manifest_2 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 2
    assert manifest_2.director_used is True


def test_old_passed_manifest_with_fallback_true_is_not_reused(repo_with_verified_project, tmp_path: Path):
    """Old manifest with director_fallback_occurred=True must be rejected in FAIL_CLOSED mode."""
    from app.media.director.models import CreativeFallbackPolicy
    repo, project_id = repo_with_verified_project
    tts = MockTTSBackend(duration_seconds=3.0)
    pipeline = MediaProductionPipeline(
        repository=repo,
        tts_backend=tts,
        base_output_dir=tmp_path / "out_reject_fallback_true",
        fallback_policy=CreativeFallbackPolicy.FAIL_CLOSED,
    )

    _, _, manifest_1 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 1

    # Overwrite manifest to simulate fallback=True but passed QA
    manifest_path = tmp_path / "out_reject_fallback_true" / project_id / "manifests" / "render_manifest.json"
    manifest_obj = RenderManifest.model_validate_json(manifest_path.read_text(encoding="utf-8"))
    manifest_dict = manifest_obj.model_dump()
    manifest_dict["director_fallback_occurred"] = True
    manifest_dict["qa_verdict"] = "PASSED"
    manifest_path.write_text(RenderManifest(**manifest_dict).model_dump_json(indent=2), encoding="utf-8")

    # Reset project state to VERIFIED
    project = repo.get_video_project(project_id)
    project.state = VideoLifecycleState.VERIFIED
    repo.save_video_project(project)

    # Must reject cache reuse and rebuild cleanly
    _, _, manifest_2 = pipeline.run_production(project_id=project_id)
    assert tts.call_count == 2
    assert manifest_2.director_fallback_occurred is False


def test_fallback_policy_change_invalidates_request_fingerprint():
    """Changing fallback_policy alters the request/production fingerprint."""
    base_params = dict(
        canonical_narration_sha256="narr_hash_123",
        render_profile_name="SHORTS_9_16",
        tts_backend="mock-tts",
        voice="voice-1",
        tts_rate="+0%",
        tts_pitch="+0Hz",
        subtitle_format="srt",
        ordered_scene_asset_hashes=["hash1", "hash2"],
        audio_mode="both",
        creative_pipeline_version="director-v3",
        content_format="EXPLAINER",
        creative_profile_name="tech-explainer",
        visual_plan_hash="plan_hash_123",
    )

    fp_fail_closed = compute_production_fingerprint(
        **base_params,
        fallback_policy="FAIL_CLOSED",
        grounding_policy_version="grounding-v2",
        creative_qa_policy_version="creative-qa-v2",
    )
    fp_preview = compute_production_fingerprint(
        **base_params,
        fallback_policy="ALLOW_LEGACY_PREVIEW",
        grounding_policy_version="grounding-v2",
        creative_qa_policy_version="creative-qa-v2",
    )

    assert fp_fail_closed != fp_preview


def test_grounding_policy_version_change_invalidates_request_fingerprint():
    """Bumping grounding_policy_version alters the request/production fingerprint."""
    base_params = dict(
        canonical_narration_sha256="narr_hash_123",
        render_profile_name="SHORTS_9_16",
        tts_backend="mock-tts",
        voice="voice-1",
        tts_rate="+0%",
        tts_pitch="+0Hz",
        subtitle_format="srt",
        ordered_scene_asset_hashes=["hash1", "hash2"],
        audio_mode="both",
        creative_pipeline_version="director-v3",
        content_format="EXPLAINER",
        creative_profile_name="tech-explainer",
        visual_plan_hash="plan_hash_123",
        fallback_policy="FAIL_CLOSED",
        creative_qa_policy_version="creative-qa-v2",
    )

    fp_v1 = compute_production_fingerprint(**base_params, grounding_policy_version="grounding-v1")
    fp_v2 = compute_production_fingerprint(**base_params, grounding_policy_version="grounding-v2")

    assert fp_v1 != fp_v2


def test_creative_qa_policy_version_change_invalidates_request_fingerprint():
    """Bumping creative_qa_policy_version alters the request/production fingerprint."""
    base_params = dict(
        canonical_narration_sha256="narr_hash_123",
        render_profile_name="SHORTS_9_16",
        tts_backend="mock-tts",
        voice="voice-1",
        tts_rate="+0%",
        tts_pitch="+0Hz",
        subtitle_format="srt",
        ordered_scene_asset_hashes=["hash1", "hash2"],
        audio_mode="both",
        creative_pipeline_version="director-v3",
        content_format="EXPLAINER",
        creative_profile_name="tech-explainer",
        visual_plan_hash="plan_hash_123",
        fallback_policy="FAIL_CLOSED",
        grounding_policy_version="grounding-v2",
    )

    fp_v1 = compute_production_fingerprint(**base_params, creative_qa_policy_version="creative-qa-v1")
    fp_v2 = compute_production_fingerprint(**base_params, creative_qa_policy_version="creative-qa-v2")

    assert fp_v1 != fp_v2


def test_request_fingerprint_is_stable_for_same_request_and_policies():
    """Identical parameters and policy versions yield an identical request fingerprint."""
    params = dict(
        canonical_narration_sha256="narr_hash_123",
        render_profile_name="SHORTS_9_16",
        tts_backend="mock-tts",
        voice="voice-1",
        tts_rate="+0%",
        tts_pitch="+0Hz",
        subtitle_format="srt",
        ordered_scene_asset_hashes=["hash1", "hash2"],
        audio_mode="both",
        creative_pipeline_version="director-v3",
        content_format="EXPLAINER",
        creative_profile_name="tech-explainer",
        visual_plan_hash="plan_hash_123",
        fallback_policy="FAIL_CLOSED",
        grounding_policy_version="grounding-v2",
        creative_qa_policy_version="creative-qa-v2",
    )

    fp_1 = compute_production_fingerprint(**params)
    fp_2 = compute_production_fingerprint(**params)

    assert fp_1 == fp_2


def test_director_pipeline_version_change_invalidates_request_fingerprint():
    """Bumping director_pipeline_version alters the request/production fingerprint."""
    base_params = dict(
        canonical_narration_sha256="narr_hash_123",
        render_profile_name="SHORTS_9_16",
        tts_backend="mock-tts",
        voice="voice-1",
        tts_rate="+0%",
        tts_pitch="+0Hz",
        subtitle_format="srt",
        ordered_scene_asset_hashes=["hash1", "hash2"],
        audio_mode="both",
        creative_pipeline_version="director-v3",
        content_format="EXPLAINER",
        creative_profile_name="tech-explainer",
        visual_plan_hash="plan_hash_123",
        fallback_policy="FAIL_CLOSED",
        grounding_policy_version="grounding-v2",
        creative_qa_policy_version="creative-qa-v2",
    )

    fp_v1 = compute_production_fingerprint(**base_params, director_pipeline_version="director-v2")
    fp_v2 = compute_production_fingerprint(**base_params, director_pipeline_version="director-v3")

    assert fp_v1 != fp_v2


